site_name: tfx
repo_name: "Tensorflow TFX"
repo_url: https://github.com/tensorflow/tfx

theme:
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

plugins:
  - search
  - autorefs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: true
            show_root_heading: true
            unwrap_annotated: true
            show_symbol_type_toc: true
            show_symbol_type_heading: true
            merge_init_into_class: true
            show_signature_annotations: true
            separate_signature: true
            signature_crossrefs: true
            group_by_category: true
            inherited_members: true
            summary: true
            filters:
              - "!^_"
              - "^__init__$"
              - "^__call__$"
              - "!^logger"
            extensions:
              - griffe_inherited_docstrings
          import:
            - https://docs.python.org/3/objects.inv
markdown_extensions:
  - admonition
  - attr_list
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

watch:
  - tfx
nav:
  - Home: index.md
  - Guide:
    - Guide: guide/index.md
    - "What's New":
      - "TFX-Addons": addons
      - "TFX Cloud Solutions": guide/solutions.md
      - "Using Keras with TFX": guide/keras
      - "Using Non-TensorFlow Frameworks in TFX": guide/non_tf
      - "Mobile & IoT: TFX for TensorFlow Lite": tutorials/tfx_for_mobile

    - "TFX Pipelines":
        - "Understanding TFX pipelines": guide/understanding_tfx_pipelines
        - "Building a TFX pipeline": guide/build_tfx_pipeline
        - "Local Pipelines": guide/build_local_pipeline

    - "TFX Standard Components":
      - "ExampleGen": guide/examplegen
      - "StatisticsGen": guide/statsgen
      - "SchemaGen": guide/schemagen
      - "ExampleValidator": guide/exampleval
      - "Transform": guide/transform
      - "Trainer": guide/trainer
      - "Tuner": guide/tuner
      - "Evaluator": guide/evaluator
      - "InfraValidator": guide/infra_validator
      - "Pusher": guide/pusher
      - "BulkInferrer": guide/bulkinferrer

    - "TFX Custom Components":
      - "Understanding custom components": guide/understanding_custom_components
      - "Python function-based components": guide/custom_function_component
      - "Container-based components": guide/container_component
      - "Fully custom components": guide/custom_component

    - "Orchestrators":
      - "Local orchestrator": guide/local_orchestrator
      - "Vertex AI Pipelines": guide/vertex
      - "Apache Airflow": guide/airflow
      - "Kubeflow Pipelines": guide/kubeflow

    - "TFX CLI":
      - "Using the TFX CLI": guide/cli

    - "Related projects":
        - "Apache Beam": "https://beam.apache.org/"
        - "MLTransform": "https://cloud.google.com/dataflow/docs/machine-learning/ml-preprocess-data"
        - "ML Metadata": guide/mlmd
        - "TensorBoard": "https://www.tensorflow.org/tensorboard"
