name: deploy-docs
on:
  workflow_dispatch:
  push:
    # Uncomment these lines before merge
    #branches:
      #- master
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Save time for cache
        run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - name: Caching
        uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - name: Install Dependencies
        run: pip install mkdocs mkdocs-material mkdocstrings[python] griffe-inherited-docstrings mkdocs-autorefs black mkdocs-jupyter
      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force
