# Github action definitions for unit-tests with PRs.

name: tfx-unit-tests
on:
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
  workflow_dispatch:

jobs:
  test:
    if: github.actor != 'copybara-service[bot]'
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        cache: 'pip'
        cache-dependency-path: |
          setup.py
          tfx/dependencies.py

    - name: Set up Bazel 5.3.0
      run: |
        # Instruction from https://docs.bazel.build/versions/master/install-ubuntu.html
        curl -sSL https://github.com/bazelbuild/bazel/releases/download/5.3.0/bazel-5.3.0-installer-linux-x86_64.sh -o bazel_installer.sh
        chmod +x bazel_installer.sh
        sudo ./bazel_installer.sh

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel
        # TODO(b/232490018): Cython need to be installed separately to build pycocotools.
        python -m pip install Cython -c ./test_constraints.txt
        TFX_DEPENDENCY_SELECTOR=NIGHTLY pip install -c ./test_constraints.txt --extra-index-url https://pypi-nightly.tensorflow.org/simple --pre --editable .[all]

    - name: Run unit tests
      shell: bash
      run: |
        pytest
