# Github action definitions for unit-tests with PRs.

name: tfx-unit-tests
on:
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
  workflow_dispatch:

jobs:
  build:
    if: github.actor != 'copybara-service[bot]'
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: Set up Bazel 5.3.0
      run: |
        # Instruction from https://docs.bazel.build/versions/master/install-ubuntu.html
        curl -sSL https://github.com/bazelbuild/bazel/releases/download/5.3.0/bazel-5.3.0-installer-linux-x86_64.sh -o bazel_installer.sh
        chmod +x bazel_installer.sh
        sudo ./bazel_installer.sh

    - name: Cache pip
      uses: actions/cache@v4
      with:
        # This path is specific to Ubuntu
        path: ~/.cache/pip
        # Look to see if there is a cache hit for the corresponding setup.py + TFX version 
        key: ${{ runner.os }}-pip-${{ hashFiles('tfx/dependencies.py') }}-
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel
        # TODO(b/232490018): Cython need to be installed separately to build pycocotools.
        python -m pip install Cython -c ./test_constraints.txt
        TFX_DEPENDENCY_SELECTOR=NIGHTLY pip install -c ./test_constraints.txt --extra-index-url https://pypi-nightly.tensorflow.org/simple --pre --editable .[all]

    - name: Run unit tests
      shell: bash
      run: |
        pytest
